### ISSUE TITLE
AutoRenewToken question

### ISSUE THREAD

**Issue by kylegalbraith** [IdentityModel/oidc-token-manager#11]
I am using the tokenExpiring function to auto renew the access token when it is close to expiring. However, will this happen indefinitely if the browser window is left open? I'd rather not let the user have an indefinite session. Do I need to write a little extra code that limits the number of times the token can be renewed?

**Comment by brockallen** [comment]
Well, at some point the user's session at the OP should expire.

**Comment by kylegalbraith** [comment]
Right, not sure I fully understand "OP" in this context. But it sounds like I would need to add some logic on the client to expire the users session?

**Comment by brockallen** [comment]
The OpenID Provider is the OP. And so yes, if you don't want that to run too long, add some client side logic.

**Comment by kylegalbraith** [comment]
So at some point Identity Server will reject the request to renew the token?

**Comment by brockallen** [comment]
Depends how you configure it. By default it issues a 10 hour fixed expiration cookie.

**Comment by kylegalbraith** [comment]
So in the auto renew request from the javascript client it passes along a cookie to IS3 and if that cookie that is presented at time of renewal is expired then it will fail to renew the access token. Is this correct? Presumably I could configure Identity Server 3 to shorten that 10 hours down.

**Comment by brockallen** [comment]
Yes.
