### ISSUE TITLE
Allow silent renewal to log user in

### ISSUE THREAD

**Issue by king2bob** [IdentityModel/oidc-token-manager#12]
Currently when a token is silently renewed the call to get a new token will fail with the error `login_required` if the user's login session has expired. In our environment the login request is handled with credentials passed by the browser, without the need for user intervention, and the redirection chain will successfully generate a token if `settings.prompt = "none"` [here](https://github.com/IdentityModel/oidc-token-manager/blob/2bf98726055c4ddc0f6e3668c60cf4fedf210c9e/oidc-token-manager.js#L476) is omitted.

I expect this is a pretty unusual case.

This [small change](https://github.com/king2bob/oidc-token-manager/commit/313d49095d598ced5bade128672cbdf14046f5eb) was the least intrusive I could think of. I can send you a PR if you want but it seems like overkill for a couple of lines and you may not even want to include this anyway.

Thanks

**Comment by brockallen** [comment]
I'd have to get my head back into the code, but what I am thinking would sense is some settings object for the silent renew and prompt could be one of those options.

**Comment by king2bob** [comment]
Sounds great, something like

``` js
var config = {
                client_id: "implicitclient",
                redirect_uri: window.location.protocol + "//" + window.location.host + "/callback.html",
                post_logout_redirect_uri: window.location.protocol + "//" + window.location.host + "/index.html",
                response_type: "id_token token",
                scope: "openid profile email read write",
                authority: "https://localhost:44333/core",                
                silent_renew: {
                    redirect_uri: window.location.protocol + "//" + window.location.host + "/frame.html",
                    allow_login_prompt: true
                }                
            };
```

would be awesome.

Thanks for the quick response.

**Comment by brockallen** [comment]
Yea, perhaps. I'm working on a project that's using this, so I'll see if I can try it out this week.

**Comment by king2bob** [comment]
Great, I'll keep an eye out for news.

**Comment by brockallen** [comment]
Would this change work for you?

https://github.com/IdentityModel/oidc-token-manager/commit/a8c127b86e94109db3d23c1f43bca7219c7ae562

**Comment by king2bob** [comment]
I'll check it out and let you know. Thanks for getting back to this.

**Comment by king2bob** [comment]
Works great. :+1:
