### ISSUE TITLE
redirect for logout not passing token

### ISSUE THREAD

**Issue by richardjharding** [IdentityModel/oidc-token-manager#13]
I've been attempting to use the token manager and hit an issue with the redirectForLogout function

On this line

```
mgr.oidcClient.createLogoutRequestAsync(mgr.id_token).then(function (url) {
```

it passes mgr.id_token but at that point that resolves to a function which means that the logout request url is incorrect?

Changing it to 

```
 mgr.oidcClient.createLogoutRequestAsync(mgr.id_token()).then(function (url) {
```

means the logout succeeds 

Or am I missing something?

**Comment by brockallen** [comment]
Wow, sorry -- missed this question.

Hmm, it should work the first way. See this sample: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/JavaScriptImplicitClient (in index.html)
