### ISSUE TITLE
Question: AngularJS Implicit Client, Silent Renew failing with invalid state when calling processTokenCallbackAsync

### ISSUE THREAD

**Issue by Condor2708** [IdentityModel/oidc-token-manager#14]
I want to know if someone experimented this issue configuring silent renew uri, 
I am using an angularjs controller as a callback url, my oidc token manager object is craeted once the application is started into a singleton factory caled AuthService.
The processResponseAsync function is throwing invalid state

Thanks

**Comment by brockallen** [comment]
Hmm, not sure. You might have to debug in some more.

**Comment by Condor2708** [comment]
I am seeing that the callback _callTokenExpiring function it is calling twice... THe only error am i seeing is 
Sometimes It happens in the first refresh ... and sometimes makes 3 or four refresh and fail again...but the following error appears always... when it fails and when the refresh token is done..

(anonymous function) @ angular.js:11655
$get @ angular.js:8596
processQueue @ angular.js:13256
(anonymous function) @ angular.js:13264
$get.Scope.$eval @ angular.js:14466
$get.Scope.$digest @ angular.js:14282
$get.Scope.$apply @ angular.js:14571
done @ angular.js:9698
completeRequest @ angular.js:9888
requestError @ angular.js:9839
cleanup @ oidc-token-manager.js:8490
message @ oidc-token-manager.js:8501

cleanup @ oidc-token-manager.js:8490 line is window.document.body.removeChild(frame);
message @ oidc-token-manager.js:8501 is 
if (handle && e.origin === location.protocol + "//" + location.host && e.source == frame.contentWindow) {

I don't know if it is angularjs that is giving troubles

**Comment by brockallen** [comment]
I'm wondering if you have the event being called outside of angular's event loop, and thus the odd behavior. I plan to release a formal angular wrapper that I use.

**Comment by Condor2708** [comment]
I'm using the oidc-token-manager into a controller and it is inyected as a constant in the angular.module constant("OidcTokenManager", OidcTokenManager). Now i remove the SilentRenewController in my code.

I will be waiting the formal wrapper to upgrade the product.
Thanks Brock!

**Comment by brockallen** [comment]
Well, the formal wrapper will look like this:

https://github.com/IdentityManager/IdentityManager/blob/master/source/Core/Assets/Scripts/App/ttIdm.js#L57

so in the mean time perhaps you can try it?
