### ISSUE TITLE
No network solution

### ISSUE THREAD

**Issue by dannycallaghan** [IdentityModel/oidc-token-manager#22]
We've integrated this into our web app and it works great, but we're now trying to think about what happens when one of our users are using our app and the network drops out.

Checking the availability of the network is not a problem.

Currently, this is what happens:
1. User is filling out some details in a web form.
2. Network drops, so silent renew fails.
3. Token expires.
4. User gets logged out, losing all the data she's just entered into the form.

Is there a way to 'postpone' the expiry of a token if there is no network? Or some other solution or ideas?

Thanks

**Comment by brockallen** [comment]
Not sure that's something we can do much about in the client library.
