### ISSUE TITLE
TypeError: undefined is not an object - evaluating 'this['ES6Promise'].Promise

### ISSUE THREAD

**Issue by phillipzada** [IdentityModel/oidc-token-manager#32]
Hi,

Just wanted to ask if anyone else has experienced this. When running Karma tests locally everything works fine, but when we test using Chutzpah (which is what our build server uses in conjunction with vstest.console.exe) we get this error:

`
TypeError: undefined is not an object (evaluating 'this['ES6Promise'].Promise
`

I've pinpointed it to this line of code

`
window.Promise = window.Promise || this['ES6Promise'].Promise; // do this to access Promise directly
`

Any suggestions?

**Comment by brockallen** [comment]
Sorry on not offering any help on this. Did you happen to sort this out?

**Comment by brockallen** [comment]
I'll close for now. Once the rewrite is out, please try it out again.
