### ISSUE TITLE
TypeScript definition

### ISSUE THREAD

**Issue by rosieks** [IdentityModel/oidc-token-manager#33]
Could you provide typescript definition for this library?

**Comment by brockallen** [comment]
If you provide it, I can include it (however that's done).

**Comment by rosieks** [comment]
Ok, I will try to prepare such definition.

**Comment by esugoi** [comment]
Hello,
I'v made a dts file some time ago and it seems to be working until now.
If it is any help to you, here are the files. I made one for the oidc client and another for the token manager.
[oidc-token-manager.txt](https://github.com/IdentityModel/oidc-token-manager/files/80097/oidc-token-manager.txt)
[oidc-client.txt](https://github.com/IdentityModel/oidc-token-manager/files/80098/oidc-client.txt)

best regards. :)

Oh, I forgot I changed to use the ES6 Promise instead.

**Comment by rosieks** [comment]
I have made pull request for this one: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7705

**Comment by brockallen** [comment]
Cool, thanks. How do we keep it in sync if we were to do any updates?

**Comment by rosieks** [comment]
The only way is to make pull requests to DefinitelyTyped.

**Comment by brockallen** [comment]
Ok, good to know.

**Comment by tonyeung** [comment]
this is done
