### ISSUE TITLE
Safari Private Mode - not working

### ISSUE THREAD

**Issue by rdelvek** [IdentityModel/oidc-token-manager#35]
It seems that since in Safari Private mode it won't write to localStorage. This is causing an issue.  Is this a common thing?  Does anyone know of a work around?  I get the same results whether I am in safari on iOS or even on an macbook.  Once I take it out of private mode, my login works perfectly.

**Comment by brockallen** [comment]
That's not surprising -- change it to use sessionStorage instead.
