### ISSUE TITLE
Uncaught ReferenceError: DefaultHttpRequest is not defined

### ISSUE THREAD

**Issue by merijndejonge** [IdentityModel/oidc-token-manager#37]
Hi,

When using the latest version available on github I get the following error.
"Uncaught ReferenceError: DefaultHttpRequest is not defined" 

Where can i find DefaultHttpRequest?

Thanks in advance for your help.

Merijn

**Comment by brockallen** [comment]
Are you using the JS file directly, or are you using the JS file from the dist folder?

**Comment by merijndejonge** [comment]
I use the JS file directly

**Comment by brockallen** [comment]
Well, that's the wrong one then :)

Use the one from the "dist" folder.

**Comment by merijndejonge** [comment]
Check.
Thanks!
