### ISSUE TITLE
5 seconds limit for silent nenewal of the token

### ISSUE THREAD

**Issue by aubm** [IdentityModel/oidc-token-manager#40]
Hello,

I noticed that `FrameLoader.prototype.loadAsync` returns a rejected promise if the renewal of the token is not done in 5 seconds or less, even though the function is invoke a minute before token expiration.

Is there a particular reason for this behavior and, if not, maybe it would be nice to be able to change those 5 seconds using some configuration parameter ?

Aurélien.

cc @davinkevin

**Comment by brockallen** [comment]
The reason it's fairly short is that the silent renew should return immediately with a result (success or failure), either because the user is logged in or not. Are you having problems with it at 5s?

**Comment by aubm** [comment]
Hum I see, but though I wonder if 5 seconds are not a bit too short. I am not suggesting to set an unreasonably long delay, but considering the fact that the code will fetch the URL a minute before the token is expired, what about setting it to, let's say 10 or 15 seconds ?

In fact, I am a little bit suprised that nobody encountered issues about that, especially with low bandwidth devices like smartphones.

**Comment by brockallen** [comment]
I'm fine with that -- please send a PR with a new default. If you want, you can also add more to make it configurable.

**Comment by aubm** [comment]
Nice :) I'll see what I can do then.

**Comment by aubm** [comment]
I closed the PR because of the suspicious amount of deletions in `dist/oidc-token-manager.js`. I used the `gulp` default task to generate it, the output file is about 800 lines only. Am I missing something ?

**Comment by brockallen** [comment]
Well, just do the PR on the original source and I can do the build to check it.

**Comment by aubm** [comment]
Ok, it seems that I forgot to `bower install` before running `gulp`, my bad.

**Comment by aubm** [comment]
Hey ! Thank you for merging :) Could you please create a new tag for me to be able to use the new parameter in my project ?

**Comment by brockallen** [comment]
Tag done

**Comment by aubm** [comment]
Nice, thank you :)
