### ISSUE TITLE
Added a note to the wiki: request_state_store 

### ISSUE THREAD

**Issue by tonyeung** [IdentityModel/oidc-token-manager#48]
Not sure if this is by design, but I was able to add a note to the wiki.
I was expecting some sort of check but it went ahead and let me edit it.
Just want to let you guys know in case you guys feel the note isn't needed.

The reason I thought to add the note was because I was getting an error because I was passing the string sessionStorage instead of the object.

**Comment by brockallen** [comment]
Ok, thanks for the update.
