### ISSUE TITLE
AuthorizationCode flow

### ISSUE THREAD

**Issue by jasonhjohnson** [IdentityModel/oidc-token-manager#52]
Hi,

Is there any way to request a "code" only rather than having to require a token or id_token? I'd like to only return the authorization code.

Thanks,
Jason

**Comment by brockallen** [comment]
For a browser based JS client?

**Comment by jasonhjohnson** [comment]
Yes. Maybe I don't understand flows. I just want the code returned rather than all the extra profile information.

**Comment by brockallen** [comment]
Code flow is for mobile/desktop and server-side apps (if needed). Browser-based JS apps use the implicit flow, which is why that's all this library supports.

**Comment by jasonhjohnson** [comment]
Well my client-side app is hosted within a .NET Core application - could I perhaps get just the code via .NETand save to client for it's use? A different question if that's outside the scope of this forum would be how I can not have all the profile info returned in the token.

**Comment by brockallen** [comment]
If the client is a server-side MVC app and you want to use the token from the server code, then you could use the OIDC middleware to obtain the token(s), and then you'd not need this library.

If you only use it from the client side code, then you could still use this library, but it would be implicit flow.
