### ISSUE TITLE
Passing state

### ISSUE THREAD

**Issue by fikkatra** [IdentityModel/oidc-token-manager#54]
How can I use the oauth2 'state' parameter to pass parameters between the request and the callback? After the callback, I need to redirect to a specific url containing a parameter that is unknown upfront, and thus should be passed upon redirecting to the auth server. There doesn't seem to be any option to pass information to the redirectForToken() or redirectForLogout() functions?

**Comment by brockallen** [comment]
Right now there's no good support for that. I'm in the middle of reworking the library now (see: https://github.com/IdentityModel/oidc-client/issues/2) and so this will be easier to support once the rework is done.

**Comment by brockallen** [comment]
This now is supported in the underlying protocol library from these recent changes: https://github.com/IdentityModel/oidc-client-js/issues/2

It's not yet released, but in the next week or so I plan to have it out. Also, these two libraries/repors might end up being merged.
