### ISSUE TITLE
typescript

### ISSUE THREAD

**Issue by mickdelaney** [IdentityModel/oidc-token-manager#6]
guys,

i've been using this lib with typescript. 
i've created a bunch of typscript definition files. i can fork the repository and add them. 
ultimately we need to add them to: https://github.com/Definitelytyped.

I've created them for both oidc-client & oidc-token-manager. its pretty simple to be fair. 

i was wondering are you or someone else already doing this ??? 

cheers.

**Comment by mickdelaney** [comment]
For example: 

interface OidcTokenManager 
{
       constructor(settings);

```
access_token: accessToken;
id_token: idToken;
profile: profile;

expires_in: number;
expired: boolean;

scopes: string[];

processTokenCallbackSilent();
processTokenCallbackAsync(callback: () => void): any;

addOnTokenObtained(callback: () => void): any;
addOnTokenRemoved(callback: () => void): any;
addOnTokenExpiring(callback: () => void): any;
addOnTokenExpired(callback: () => void): any;

removeToken(): void;

redirectForToken(): void;
redirectForLogout(): void;
```

}

**Comment by brockallen** [comment]
I was going to start here: https://github.com/IdentityModel/oidc-client/issues/2

**Comment by mickdelaney** [comment]
Ok. let me know if you want any help.

**Comment by brockallen** [comment]
I might. Maybe you'd be willing to share with me what you've done so I can use that as a starting point?

**Comment by luiz-brasil** [comment]
Great... I was thinkig about doing this. Let me know if you want any help!

**Comment by brockallen** [comment]
Well, we'd need to first start in the oidc-client project, since the token manager is built on it. Then we can figure out what's next.

**Comment by mickdelaney** [comment]
ok i'll close this and fork the oidc-client repository.

**Comment by ellern** [comment]
@mickdelaney did you publish your typscript definition files for this and oidc-client anywhere?

**Comment by mickdelaney** [comment]
sorry guys not been around for xmas. it didnt publish anything, its all embedded in my code but we'll look to contribute to anything if someone has a repository etc.

**Comment by iberodev** [comment]
I'm new to TypeScript, but does this mean that eventually we will be able to do something like:
`tsd install oidc-token-manager --resolve --save`
and the definition file will be downloaded and added under the project's typings folder so that VS won't complain about not finding names such as OidcTokenManager?

**Comment by brockallen** [comment]
I don't know TS either, so I don't even know what that means.

But today you can get oidc-client and oidc-token-manager via npm and bower. Others have told me it's also available via jspm.

**Comment by ellern** [comment]
@realavaloro you can already use it with Typescript, just declare it as type `any`. It won't give you the typescript compile type checking or intellisense in VS.

**Comment by iberodev** [comment]
Excellent! Thank you @ellern

Just a quick note for anybody who finds this thread, I just found out there is a type definition for oidc-token-manager available in tsd as per https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7705, 
so by running `tsd install oidc-token-manager --resolve --save` we can now enjoy oidc-token-manager in TypeScript with Intellisense + Compile time check in our IDE
