### ISSUE TITLE
Callback to different website

### ISSUE THREAD

**Issue by vnexter** [IdentityModel/oidc-token-manager#64]
I am using my brochure page or information to give user information about our online app (hosted seprately) myapp.com . There is a login button which redirects using redirectForToken() in OIDC token manager) using Identity Server 3 for tokens .

But redirect url is myotherapp.com - on callback I cant use processTokenCallbackAsync() and throws error about "no request state found".

Please let me know how to solve it.

Many thanks.

**Comment by vnexter** [comment]
I am guessing its to do with state in the localStorage not there for obvious reason in the myotherapp.com.

Is there any way out ?

regards

**Comment by brockallen** [comment]
The protocols require that the redirect URI be back to the app that initiated the request. If you want the other app to get the user logged in, then you need to first redirect the user to that app and from that app initiate the login process.

**Comment by vnexter** [comment]
Many thanks.
