### ISSUE TITLE
IE9 and javascript oidc-client.js ver 1.0.1 build

### ISSUE THREAD

**Issue by mbelfer** [IdentityModel/oidc-token-manager#66]
Hi,

I am using oidc-client.js and all was good until one of the users reported problem with IE9.

when issuing a call to: 
`var mgr = new Oidc.UserManager(settings);`

I get:

```
SCRIPT438: Object doesn't support property or method 'apply' 
app.js, line 39 character 1
```

Thank you

Mark

**Comment by brockallen** [comment]
I have a feeling there are many things that won't work in IE9. I can take a look when I get some time. You can do some investigation in the meantime.

**Comment by mbelfer** [comment]
thank you Brock,

there are 2 problems to do with that
1. use of console object in IE9
2. logger.info.apply does not have apply method

once I resolved the above mentioned - I am getting 

> "Unhandled promise rejectionError: Access is denied.". 

IE9 does not support CORS but I was under impression by reading other posts that this should be working, but at the same time based on your response I am not sure if it should ;~)

Please advise

Thank you
Mark

**Comment by brockallen** [comment]
This repo is retired. use https://github.com/IdentityModel/oidc-client-js/ instead.
