### ISSUE TITLE
Single sign-out

### ISSUE THREAD

**Issue by Astimus** [IdentityModel/oidc-token-manager#69]
At this time I'm using this library in two my angular applications. And I want to implement single sign-out functionallity. Is there any examples of how to implement this feature? Does this library support this feature? Or do I need to use some type of workaround? Maybe new library _oidc-client_ support this feature and better to migrate my current applications to new library?

**Comment by brockallen** [comment]
This library is deprecated -- you should be using oidc-client instead: https://github.com/IdentityModel/oidc-client-js/.
