### ISSUE TITLE
silent renew error interaction_required

### ISSUE THREAD

**Issue by Herowin8x** [IdentityModel/oidc-token-manager#71]
Hi brockallen,

I refered your sample using OIDC, i have met issue is "silent renew error interaction_required"
I have spent more time to investigate this issue, i have also tried to set cookie expire time on Identity Server
but silent renew not working for me.

Any suggestions?

Thanks
Tuan Nguyen.

**Comment by brockallen** [comment]
This repo is retired. use https://github.com/IdentityModel/oidc-client-js/ instead.

**Comment by Herowin8x** [comment]
Thanks brockallen, it worked with me.
