### ISSUE TITLE
Question: TokenManager and redirectForLogout 

### ISSUE THREAD

**Issue by Condor2708** [IdentityModel/oidc-token-manager#9]
I have an SPA application using TokenManager library.
I'm logged in into the application and I want to logout and show the Login Form again. 
If I call redirectForLogout() it is redirecting me to the IdentityServer logout page and then redirecting me again to my SPA application

Which is the best way I can manage this without doing too many redirects? 
Thanks

**Comment by brockallen** [comment]
You need to redirect to the OP if you want to logout of the token service. If you don't, then you don't have to do the redirect.

**Comment by Condor2708** [comment]
There is any option to redirect to the OP and show the login page in only one instruction? It will be a good idea?  

Thanks

**Comment by brockallen** [comment]
You can pass the OIDC prompt=login param to force re-authentication. Check the spec.

**Comment by Condor2708** [comment]
Thanks Brock!!!
